//Approved=false
//DriverEntry
#define fun_DriverEntry DriverEntry
//ds4_xusbEvtDeviceAdd
#define fun_WDF_DRIVER_DEVICE_ADD ds4_xusbEvtDeviceAdd
//ds4_xusbEvtIoDeviceControl
#define fun_WDF_IO_QUEUE_IO_DEVICE_CONTROL ds4_xusbEvtIoDeviceControl
//ds4_xusbEvtDriverContextCleanup
#define fun_WDF_OBJECT_CONTEXT_CLEANUP ds4_xusbEvtDriverContextCleanup
